### ISSUE TITLE
win7 vs2015 compiler error

### ISSUE THREAD

**Issue by biaozhunhuge** [kzampog/cilantro#10]
tips:
file: cilantro-master\include\cilantro/space_transformations.hpp 
10line
error C2027: use of undefined type 'Eigen::Transform<ScalarT,EigenDim,1,0>'
I Try some ,but it still not work

**Comment by kzampog** [comment]
Hi!

Maybe Eigen (3.3 or later) is not in the include path? Please see #6 for building under Windows (TL:DR: cilantro can be compiled with VS, but OpenMP will not be enabled). Unfortunately, I did not get a chance yet to work on polishing native Windows builds.

Cheers!

**Comment by shekhar331** [comment]
Hello,
I am facing the same issue on Visual Studio. Can you please take a look into the windows build. i am specifically needing the ICP Point Plane implementation

Thanks

**Comment by kzampog** [comment]
Hi!

Sorry for the late reply. I didn't get a chance to investigate yet, but I will probably have some free time in the next few days!
