### ISSUE TITLE
is there any plan to write cuda?

### ISSUE THREAD

**Issue by mjjdick** [kzampog/cilantro#15]
Hi, great work!
I just want to ask, is there any plan to add cuda code to improve the pointcloud process performance?

**Comment by kzampog** [comment]
Hi! I would like to have CUDA implementations (at least for certain processes like non-rigid registration) at some point, but this is unlikely to happen in the immediate future. Thank you for your interest!

**Comment by mjjdick** [comment]
@kzampog Okay! looking forward!
