### ISSUE TITLE
Running examples

### ISSUE THREAD

**Issue by tanismar** [kzampog/cilantro#27]
Hi, 
I managed to compile and install the library without any problem, but whenever I try to run any example, I get the following error:
./ply_io: error while loading shared libraries: librealsense2.so.2.20: cannot open shared object file: No such file or directory
which is weird because librealsense is not even a requirement in the CMakeLists. Do you have any idea what might be creating this issue, and/or how to fix it?

**Comment by kzampog** [comment]
Hi!

`cilantro` does definitely not depend on librealsense. Maybe Pangolin was built with realsense support and then the realsense binaries were somehow misplaced?

I would try rebuilding Pangolin. Please let me know of any findings :)

**Comment by tanismar** [comment]
Hi !
Yeah, that worked! Thanks a lot for the tip!
