### ISSUE TITLE
where is the lib file

### ISSUE THREAD

**Issue by bigdimboom** [kzampog/cilantro#28]
I built the project with CMakeList you provided. But, where is the lib file? I can't find it in the install folder.

I built without enabling Pangolin.

![image](https://user-images.githubusercontent.com/6119906/57259489-db80c780-702d-11e9-9e82-a2c72ecfb3a9.png)

**Comment by kzampog** [comment]
Hi!

Unfortunately, I am not sure where VS places the lib/dll binaries (the install cmake commands probably do not work in Windows -- see also #6). Please note that most of the library is header-only and only a small part (I/O and qhull) is actually compiled (especially if you disable the visualization stuff). The (old) OpenMP version supported by VS will probably give you trouble (see also #6) when compiling your executables, as we make use of functionality introduced in more recent versions. If performance is not crucial, you could simply comment out the offending pragmas.
