### ISSUE TITLE
Installing on a local path

### ISSUE THREAD

**Issue by fabiopoiesi** [kzampog/cilantro#4]
I tried to install the library on a local path, but it seems the library doesn't see use the prefix path correctly.
When I did cmake I set 

CMAKE_INSTALL_PREFIX             /home/fabio/Libraries/cilantro/installed

then when I did make install, it tried to install it in /usr/local/

:~/Libraries/cilantro/build$ make install
[ 64%] Built target cilantro
[ 66%] Built target kmeans_example
[ 68%] Built target normal_estimation_example
[ 70%] Built target voxel_grid_example
[ 73%] Built target principal_component_analysis_example
[ 75%] Built target rigid_transform_estimator_example
[ 77%] Built target kd_tree_example
[ 79%] Built target ply_io_example
[ 82%] Built target matrix_io_example
[ 84%] Built target visualizer_example
[ 86%] Built target space_region_example
[ 88%] Built target iterative_closest_point_example
[ 91%] Built target connected_component_segmentation_example
[ 93%] Built target image_viewer_example
[ 95%] Built target convex_hull_example
[ 97%] Built target plane_estimator_example
[100%] Built target image_point_cloud_conversions_example
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/libcilantro.so
-- Set runtime path of "/usr/local/lib/libcilantro.so" to ""
-- Up-to-date: /usr/local/include
CMake Error at cmake_install.cmake:72 (file):
  file INSTALL cannot set permissions on "/usr/local/include"

Makefile:93: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by kzampog** [comment]
Hi!

It seems I had absolute install paths in make file - install prefix should be working now. Thanks for the catch!

Best,
Kostas
