### ISSUE TITLE
it sames I can not read ply file?

### ISSUE THREAD

**Issue by HeXu1** [kzampog/cilantro#43]
coding:
"   std::string file_path="data/test.ply";
    cilantro::PointCloud3f cloud(file_path);"

when I was building,the output is 
"/usr/local/include/cilantro/utilities/ply_io.hpp:11: undefined reference to `tinyply::PlyFile::PlyFile()'
/usr/local/include/cilantro/utilities/ply_io.hpp:12: undefined reference to `tinyply::PlyFile::parse_header(std::istream&)'
/usr/local/include/cilantro/utilities/ply_io.hpp:11: undefined reference to `tinyply::PlyFile::~PlyFile()'...."

And when I try to use the visualizer,the output is :
" undefined reference to `cilantro::Visualizer::Visualizer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/cidi/learning_code/myLocalization1/src/jiqunLocalization.cc:569: undefined reference to `cilantro::Visualizer::spinOnce()'
/home/cidi/learning_code/myLocalization1/src/jiqunLocalization.cc:563: undefined reference to `cilantro::Visualizer::~Visualizer()'
/home/cidi/learning_code/myLocalization1/src/jiqunLocalization.cc:563: undefined reference to `cilantro::Visualizer::~Visualizer()' "

the Pangolin is builded fine.

I can running your demo fine ,but it does not work in my project~ 
hope for you answer,thanks.

**Comment by HeXu1** [comment]
and I just can run Kdtree example, it doesn't need read ply data or visualizer~

**Comment by kzampog** [comment]
Hi,

Apologies for the late reply. It seems you are not linking against the library. If you used the default CMake settings for building `cilantro` and also use CMake for your project, you could simply try a `CMakeLists.txt` that looks like:

```
cmake_minimum_required(VERSION 3.9)
project(my_project)

find_package(cilantro)

add_executable(test_app test_app.cpp)
target_link_libraries(test_app ${cilantro_LIBRARIES})
```

Let me know if you still run into issues!

**Comment by HeXu1** [comment]
oh ,it works.
thanks for your help.Wish everything goes well.

**Comment by kzampog** [comment]
Great! No problem :)
