### ISSUE TITLE
Doesn't build with current Pangolin

### ISSUE THREAD

**Issue by timhutton** [kzampog/cilantro#46]
I see the .travis.yml downloads a snapshot of an older Pangolin. Trying to build with the current version of Pangolin gives errors, as some files have moved, etc.

**Comment by kzampog** [comment]
Hi,

That should not be the case: it pulls the latest commit from master (using the same URL as the "Download ZIP" repo link).

There's two possibilities that I can think of:
1) Pangolin was not built with Eigen enabled (just recompile having Eigen installed)
2) You have a different version of Pangolin installed (e.g. via make install)

Please note that you may encounter errors compiling the ICP examples on Ubuntu 16.04 if you use the Eigen version from the distribution repos. Ubuntu 18.04 should work fine :)

Let me know if you still have trouble building!

**Comment by timhutton** [comment]
OK, my bad. Thanks.
