### ISSUE TITLE
Radius search using kdtree always returns sorted result.

### ISSUE THREAD

**Issue by Austin1511** [kzampog/cilantro#55]
Thank you for your great project!
When I use KDTree.radiusSearch() in a huge for loop, it always returns the sorted result, and the sorting feature slows down the for loop. Even I changed the sorted class member to false in the nanoflann::SearchParams, I still get the sorted result. Do you know some way to disable the sort. Thank you for your help!

**Comment by wannesvanloock** [comment]
Radius search [indeed returns sorted results](https://github.com/kzampog/cilantro/blob/c11cc8d9d1580760e46730ac9aa0d4c948e0f118/include/cilantro/core/kd_tree.hpp#L242). I think it should be straightforward to make this configurable.

If only interested in a limited number of points, I would recommend using `kNNInRadiusSearch` which I think will be more efficient.

**Comment by Austin1511** [comment]
@wannesvanloock Thank you ! That solves my problem. I notice that there is another problem with the radiusSearch() funtion. When I want to search a area with 5 radius, I have to pass 5 * 5 to the radius parameter to get the correct result.

**Comment by kzampog** [comment]
This was done to imitate the way `nanoflann` works. Please note that distances returned in search results are also squared!

**Comment by Austin1511** [comment]
Ok, understood. A comment on the function may be appreciated. Thanks again!
