### ISSUE TITLE
performance comparisons to PCL

### ISSUE THREAD

**Issue by cstathis** [kzampog/cilantro#8]
In your arxiv paper you have some graphs showing a performance improvement over PCL on a dataset. Do you have an explanation for why cilantro is faster, particularly for ICP? How much of the speed-up is due to multi-threading?

**Comment by kzampog** [comment]
Hi!

Multi-threading (especially in the correspondence search phase) is indeed responsible for most of the speedup. The kd-tree implementation used here itself is also faster (see https://github.com/jlblancoc/nanoflann, PCL uses FLANN), so I would expect that single-threaded performance would be also better (but I haven't tested for that).

Also, I forgot to mention in the paper that the experiments were run on an i7-6700K (4C/8T). Running times on an 8-core Ryzen 1800X showed good performance scaling as well.
