### ISSUE TITLE
upsampling point clouds?

### ISSUE THREAD

**Issue by antithing** [kzampog/cilantro#9]
Does cilantro have this functionality? i need to upsample and smooth depth camera data.  Thanks!

**Comment by kzampog** [comment]
Hi!

Unfortunately, cilantro does not have such functionality at this point.
What set of functions would be needed to accommodate your task?

Best,
Kostas

**Comment by kzampog** [comment]
Hi!

Unfortunately, cilantro does not have such functionality at this point.
What set of functions would be needed to accommodate your task?
